# what is pandas

-> Pandas is an open-source Python library used for data manipulation, analysis, and cleaning. It provides powerful and easy-to-use data structures for working with tabular and time-series data.
-> Data Analysis
-> Data manipulation
-> Data Handling
-> Data Wrangling

# importing Pandas

In [2]:
import pandas as pd

In [3]:
# installing pandas

In [4]:
!pip install pandas

Requirement already satisfied: pandas in c:\users\kusha\anaconda3\lib\site-packages (2.3.3)
Requirement already satisfied: numpy>=1.26.0 in c:\users\kusha\anaconda3\lib\site-packages (from pandas) (2.3.5)
Requirement already satisfied: python-dateutil>=2.8.2 in c:\users\kusha\anaconda3\lib\site-packages (from pandas) (2.9.0.post0)
Requirement already satisfied: pytz>=2020.1 in c:\users\kusha\anaconda3\lib\site-packages (from pandas) (2025.2)
Requirement already satisfied: tzdata>=2022.7 in c:\users\kusha\anaconda3\lib\site-packages (from pandas) (2025.2)
Requirement already satisfied: six>=1.5 in c:\users\kusha\anaconda3\lib\site-packages (from python-dateutil>=2.8.2->pandas) (1.17.0)

In [5]:
# create series - one dimensional data

In [3]:
cars = pd.Series(["BMW","Tata","Audi","Toyota","Mahindra","Thar"])
print(cars)

0         BMW
1        Tata
2        Audi
3      Toyota
4    Mahindra
5        Thar
dtype: object

In [4]:
colours = pd.Series(["Red","Blue","Green","White","Maroon"])
print(colours)

0       Red
1      Blue
2     Green
3     White
4    Maroon
dtype: object

In [22]:
# creating Data Frame - Multi demensional data

In [5]:
cars_data = pd.DataFrame({"cars_type":cars,"colours_type":colours})
(cars_data)

  cars_type colours_type
0       BMW          Red
1      Tata         Blue
2      Audi        Green
3    Toyota        White
4  Mahindra       Maroon
5      Thar          NaN

In [6]:
fruits = pd.Series(["Mango","Apple","Banana","Orange","watermelon"])
print(fruits)

0         Mango
1         Apple
2        Banana
3        Orange
4    watermelon
dtype: object

In [7]:
colours = pd.Series(["Yellow","Red","Yellow","orange","Green"])
colours

0    Yellow
1       Red
2    Yellow
3    orange
4     Green
dtype: object

In [8]:
fruits_data = pd.DataFrame({"Fruits_type":fruits,"colours_type":colours})
fruits_data

  Fruits_type colours_type
0       Mango       Yellow
1       Apple          Red
2      Banana       Yellow
3      Orange       orange
4  watermelon        Green

# example 1

In [9]:
fruits = pd.Series(["Mangoes","Banana","Grapes"," Watermelon"])
fruits_price = pd.Series([100,150,200,250])
fruits_data = pd. DataFrame({"fruits_type": fruits ," price_type": fruits_price})
fruits_data

   fruits_type   price_type
0      Mangoes          100
1       Banana          150
2       Grapes          200
3   Watermelon          250

# 2.importing data

There are Three Methods we can use :
1. Direct from local Machine(server)
2. Direct from local Machine from different location 
3. From any link

In [10]:
Cars_Data=pd.read_csv("Cars_Data.csv")
Cars_Data

   S.No            Car Brand  Colour Odometer (km)  Doors    Price
0     1       Toyota Corolla   White        45,000      4   850000
1     2           Honda City   Black        38,500      4   920000
2     3        Hyundai Creta  Silver        27,000      4  1250000
3     4  Maruti Suzuki Swift     Red        52,300      4   650000
4     5           Kia Seltos    Blue        18,900      4  1450000
5     6      Mahindra XUV700    Grey        22,100      4  2100000
6     7    Tata Motors Nexon   White        31,400      4   980000
7     8        Ford EcoSport  Orange        60,000      4   720000
8     9      Volkswagen Polo  Yellow        48,200      4   780000
9    10               BMW X1   Black        15,600      4  3950000

In [11]:
Cars_Data1 = pd.read_csv("C:/Users/kusha/OneDrive/Desktop/Cars_Data.csv")
Cars_Data1

   S.No            Car Brand  Colour Odometer (km)  Doors    Price
0     1       Toyota Corolla   White        45,000      4   850000
1     2           Honda City   Black        38,500      4   920000
2     3        Hyundai Creta  Silver        27,000      4  1250000
3     4  Maruti Suzuki Swift     Red        52,300      4   650000
4     5           Kia Seltos    Blue        18,900      4  1450000
5     6      Mahindra XUV700    Grey        22,100      4  2100000
6     7    Tata Motors Nexon   White        31,400      4   980000
7     8        Ford EcoSport  Orange        60,000      4   720000
8     9      Volkswagen Polo  Yellow        48,200      4   780000
9    10               BMW X1   Black        15,600      4  3950000

In [13]:
newdata = pd.read_csv("https://raw.githubusercontent.com/mwaskom/seaborn-data/master/iris.csv")
newdata

     sepal_length  sepal_width  petal_length  petal_width    species
0             5.1          3.5           1.4          0.2     setosa
1             4.9          3.0           1.4          0.2     setosa
2             4.7          3.2           1.3          0.2     setosa
3             4.6          3.1           1.5          0.2     setosa
4             5.0          3.6           1.4          0.2     setosa
..            ...          ...           ...          ...        ...
145           6.7          3.0           5.2          2.3  virginica
146           6.3          2.5           5.0          1.9  virginica
147           6.5          3.0           5.2          2.0  virginica
148           6.2          3.4           5.4          2.3  virginica
149           5.9          3.0           5.1          1.8  virginica

[150 rows x 5 columns]

# importing Excel Data

In [ ]:
excel_data=pd.read_xlsx

# 3.Export the Data

In [35]:
exported_data = newdata.to_csv("exported_data.csv")

# 4. Describing Data in pandas

In [36]:
Cars_Data1

   S.No            Car Brand  Colour Odometer (km)  Doors    Price
0     1       Toyota Corolla   White        45,000      4   850000
1     2           Honda City   Black        38,500      4   920000
2     3        Hyundai Creta  Silver        27,000      4  1250000
3     4  Maruti Suzuki Swift     Red        52,300      4   650000
4     5           Kia Seltos    Blue        18,900      4  1450000
5     6      Mahindra XUV700    Grey        22,100      4  2100000
6     7    Tata Motors Nexon   White        31,400      4   980000
7     8        Ford EcoSport  Orange        60,000      4   720000
8     9      Volkswagen Polo  Yellow        48,200      4   780000
9    10               BMW X1   Black        15,600      4  3950000

In [47]:
# how to check data type pf each column

In [14]:
Cars_Data1.dtypes

S.No              int64
Car Brand        object
Colour           object
Odometer (km)    object
Doors             int64
Price             int64
dtype: object

# Statistical Overveiw of data

In [15]:
Cars_Data1.describe()

           S.No  Doors         Price
count  10.00000   10.0  1.000000e+01
mean    5.50000    4.0  1.365000e+06
std     3.02765    0.0  1.006857e+06
min     1.00000    4.0  6.500000e+05
25%     3.25000    4.0  7.975000e+05
50%     5.50000    4.0  9.500000e+05
75%     7.75000    4.0  1.400000e+06
max    10.00000    4.0  3.950000e+06

In [16]:
Cars_Data1

   S.No            Car Brand  Colour Odometer (km)  Doors    Price
0     1       Toyota Corolla   White        45,000      4   850000
1     2           Honda City   Black        38,500      4   920000
2     3        Hyundai Creta  Silver        27,000      4  1250000
3     4  Maruti Suzuki Swift     Red        52,300      4   650000
4     5           Kia Seltos    Blue        18,900      4  1450000
5     6      Mahindra XUV700    Grey        22,100      4  2100000
6     7    Tata Motors Nexon   White        31,400      4   980000
7     8        Ford EcoSport  Orange        60,000      4   720000
8     9      Volkswagen Polo  Yellow        48,200      4   780000
9    10               BMW X1   Black        15,600      4  3950000

# view Data from top

In [17]:
Cars_Data1.head()

   S.No            Car Brand  Colour Odometer (km)  Doors    Price
0     1       Toyota Corolla   White        45,000      4   850000
1     2           Honda City   Black        38,500      4   920000
2     3        Hyundai Creta  Silver        27,000      4  1250000
3     4  Maruti Suzuki Swift     Red        52,300      4   650000
4     5           Kia Seltos    Blue        18,900      4  1450000

Cars_Data1.tail(9)

# More info from data

In [18]:
Cars_Data1.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 10 entries, 0 to 9
Data columns (total 6 columns):
 #   Column         Non-Null Count  Dtype
---  ------         --------------  -----
 0   S.No           10 non-null     int64
 1   Car Brand      10 non-null     object
 2   Colour         10 non-null     object
 3   Odometer (km)  10 non-null     object
 4   Doors          10 non-null     int64
 5   Price          10 non-null     int64
dtypes: int64(3), object(3)
memory usage: 612.0+ bytes

In [59]:
# calculate mean externally

In [19]:
Cars_Data1.mean(numeric_only=True)

S.No           5.5
Doors          4.0
Price    1365000.0
dtype: float64

In [20]:
Cars_Data1.sum(numeric_only=True)

S.No           55
Doors          40
Price    13650000
dtype: int64

# Access any column/columns

In [21]:
Cars_Data1.columns

Index(['S.No', 'Car Brand', 'Colour', 'Odometer (km)', 'Doors', 'Price'], dtype='object')

In [22]:
Cars_Data1["Car Brand"]

0         Toyota Corolla
1             Honda City
2          Hyundai Creta
3    Maruti Suzuki Swift
4             Kia Seltos
5        Mahindra XUV700
6      Tata Motors Nexon
7          Ford EcoSport
8        Volkswagen Polo
9                 BMW X1
Name: Car Brand, dtype: object

# 5. viewing

In [23]:
Cars_Data1.head(2)

   S.No       Car Brand Colour Odometer (km)  Doors   Price
0     1  Toyota Corolla  White        45,000      4  850000
1     2      Honda City  Black        38,500      4  920000

In [24]:
# Create a simple a series of animals
import pandas as pd
animals=pd.Series(["cat","dog","bird","snake","lion"],index=[3,9,8,12,5])
animals.loc[5]
animals.loc[9]
# loc[] takes an integer or label as input it gives the location.

'dog'

In [25]:
# iloc[] represent exact index from starting(by default)
student=pd.Series(["Vinay","pranitha","rishitha","bhanusri"],index=[20,30,35,40])
student.loc[30] 
student.iloc[1]

'pranitha'

In [26]:
student=pd.Series(["Vinay","pranitha","rishitha","bhanusri"],index=[20,30,35,40])
student.iloc[1]

'pranitha'

# How to select any specific column

In [27]:
Cars_Data1["Car Brand"]

0         Toyota Corolla
1             Honda City
2          Hyundai Creta
3    Maruti Suzuki Swift
4             Kia Seltos
5        Mahindra XUV700
6      Tata Motors Nexon
7          Ford EcoSport
8        Volkswagen Polo
9                 BMW X1
Name: Car Brand, dtype: object

In [28]:
Cars_Data

   S.No            Car Brand  Colour Odometer (km)  Doors    Price
0     1       Toyota Corolla   White        45,000      4   850000
1     2           Honda City   Black        38,500      4   920000
2     3        Hyundai Creta  Silver        27,000      4  1250000
3     4  Maruti Suzuki Swift     Red        52,300      4   650000
4     5           Kia Seltos    Blue        18,900      4  1450000
5     6      Mahindra XUV700    Grey        22,100      4  2100000
6     7    Tata Motors Nexon   White        31,400      4   980000
7     8        Ford EcoSport  Orange        60,000      4   720000
8     9      Volkswagen Polo  Yellow        48,200      4   780000
9    10               BMW X1   Black        15,600      4  3950000

In [29]:
print(Cars_Data1["Odometer (km)"].head(10))

0    45,000
1    38,500
2    27,000
3    52,300
4    18,900
5    22,100
6    31,400
7    60,000
8    48,200
9    15,600
Name: Odometer (km), dtype: object

# To convert object d_types to integer d_types

In [30]:
Cars_Data.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 10 entries, 0 to 9
Data columns (total 6 columns):
 #   Column         Non-Null Count  Dtype
---  ------         --------------  -----
 0   S.No           10 non-null     int64
 1   Car Brand      10 non-null     object
 2   Colour         10 non-null     object
 3   Odometer (km)  10 non-null     object
 4   Doors          10 non-null     int64
 5   Price          10 non-null     int64
dtypes: int64(3), object(3)
memory usage: 612.0+ bytes

In [31]:
Cars_Data["Price"] = Cars_Data["Price"].fillna(0).astype(int)

# converting into lower case

In [32]:
Cars_Data["Car Brand"]=Cars_Data["Car Brand"].str.lower()
Cars_Data

   S.No            Car Brand  Colour Odometer (km)  Doors    Price
0     1       toyota corolla   White        45,000      4   850000
1     2           honda city   Black        38,500      4   920000
2     3        hyundai creta  Silver        27,000      4  1250000
3     4  maruti suzuki swift     Red        52,300      4   650000
4     5           kia seltos    Blue        18,900      4  1450000
5     6      mahindra xuv700    Grey        22,100      4  2100000
6     7    tata motors nexon   White        31,400      4   980000
7     8        ford ecosport  Orange        60,000      4   720000
8     9      volkswagen polo  Yellow        48,200      4   780000
9    10               bmw x1   Black        15,600      4  3950000

In [36]:
car_sales_missing_data=pd.read_csv("C:/Users/kusha/Downloads/car-sales-missing-data.csv")
car_sales_missing_data

     Make Colour  Odometer  Doors    Price
0  Toyota  White  150043.0    4.0   $4,000
1   Honda    Red   87899.0    4.0   $5,000
2  Toyota   Blue       NaN    3.0   $7,000
3     BMW  Black   11179.0    5.0  $22,000
4  Nissan  White  213095.0    4.0   $3,500
5  Toyota  Green       NaN    4.0   $4,500
6   Honda    NaN       NaN    4.0   $7,500
7   Honda   Blue       NaN    4.0      NaN
8  Toyota  White   60000.0    NaN      NaN
9     NaN  White   31600.0    4.0   $9,700

In [42]:
car_sales_missing_data["Odometer"]= car_sales_missing_data["Odometer"].fillna(car_sales_missing_data["Odometer"].mean())
car_sales_missing_data

     Make Colour       Odometer  Doors    Price
0  Toyota  White  150043.000000    4.0   $4,000
1   Honda    Red   87899.000000    4.0   $5,000
2  Toyota   Blue   92302.666667    3.0   $7,000
3     BMW  Black   11179.000000    5.0  $22,000
4  Nissan  White  213095.000000    4.0   $3,500
5  Toyota  Green   92302.666667    4.0   $4,500
6   Honda    NaN   92302.666667    4.0   $7,500
7   Honda   Blue   92302.666667    4.0      NaN
8  Toyota  White   60000.000000    NaN      NaN
9     NaN  White   31600.000000    4.0   $9,700

In [44]:
car_sales_missing_data["Colour"]= car_sales_missing_data["Colour"].fillna(car_sales_missing_data["Odometer"].mode())
car_sales_missing_data["Colour"]

0    White
1      Red
2     Blue
3    Black
4    White
5    Green
6      NaN
7     Blue
8    White
9    White
Name: Colour, dtype: object

In [48]:
car_sales_missing_data["Colour"]= car_sales_missing_data["Colour"].fillna(car_sales_missing_data["Odometer"].mode().index[0])
car_sales_missing_data["Colour"]

0    White
1      Red
2     Blue
3    Black
4    White
5    Green
6        0
7     Blue
8    White
9    White
Name: Colour, dtype: object

# Adding New Column in Dataframe

In [50]:
seats = pd.Series([5,6,5,5,5,5,5,5,5,5])
car_sales_missing_data["seats"]=seats
car_sales_missing_data

     Make Colour       Odometer  Doors    Price  seats
0  Toyota  White  150043.000000    4.0   $4,000      5
1   Honda    Red   87899.000000    4.0   $5,000      6
2  Toyota   Blue   92302.666667    3.0   $7,000      5
3     BMW  Black   11179.000000    5.0  $22,000      5
4  Nissan  White  213095.000000    4.0   $3,500      5
5  Toyota  Green   92302.666667    4.0   $4,500      5
6   Honda      0   92302.666667    4.0   $7,500      5
7   Honda   Blue   92302.666667    4.0      NaN      5
8  Toyota  White   60000.000000    NaN      NaN      5
9     NaN  White   31600.000000    4.0   $9,700      5

In [59]:
car_sales_missing_data["passed road safety"]=True
car_sales_missing_data

     Make Colour       Odometer  Doors    Price  seats  passed road safety
0  Toyota  White  150043.000000    4.0   $4,000      5                True
1   Honda    Red   87899.000000    4.0   $5,000      6                True
2  Toyota   Blue   92302.666667    3.0   $7,000      5                True
3     BMW  Black   11179.000000    5.0  $22,000      5                True
4  Nissan  White  213095.000000    4.0   $3,500      5                True
5  Toyota  Green   92302.666667    4.0   $4,500      5                True
6   Honda      0   92302.666667    4.0   $7,500      5                True
7   Honda   Blue   92302.666667    4.0      NaN      5                True
8  Toyota  White   60000.000000    NaN      NaN      5                True
9     NaN  White   31600.000000    4.0   $9,700      5                True